Traceback (most recent call last):
  File "/scripts/tests/test_egd_spectra.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 52, in <module>
    import matplotlib.colorbar
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/colorbar.py", line 19, in <module>
    from matplotlib import _api, cbook, collections, cm, colors, contour, ticker
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/contour.py", line 13, in <module>
    from matplotlib.backend_bases import MouseButton
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backend_bases.py", line 45, in <module>
    from matplotlib import (
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/text.py", line 16, in <module>
    from .font_manager import FontProperties
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/font_manager.py", line 1551, in <module>
    fontManager = _load_fontmanager()
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/font_manager.py", line 1546, in _load_fontmanager
    json_dump(fm, fm_path)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/font_manager.py", line 958, in json_dump
    with cbook._lock_path(filename), open(filename, 'w') as fh:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/cbook/__init__.py", line 1814, in _lock_path
    raise TimeoutError("""\
TimeoutError: Lock error: Matplotlib failed to acquire the following lock file:
    /root/.cache/matplotlib/fontlist-v330.json.matplotlib-lock
This maybe due to another process holding this lock file.  If you are sure no
other Matplotlib process is running, remove this file and try again.
slurmstepd: error: *** STEP 14010790.0 ON nid007103 CANCELLED AT 2023-08-17T19:50:17 ***
slurmstepd: error: *** JOB 14010790 ON nid007103 CANCELLED AT 2023-08-17T19:50:17 ***
